import 'package:restaurants/core/constants/app_assets_manager.dart';
import 'package:restaurants/features/home/model/restaurant_model.dart';

List<RestaurantModel> restaurants = [
  RestaurantModel(
      name: 'Ramen House',
      cuisineType: 'Japanese',
      maxPrice: 1700,
      minPrice: 1020,
      averageRating: 4.5,
      logo: AppAssetsManager.crapImg),
  RestaurantModel(
      name: 'Diner Delight',
      cuisineType: 'American',
      maxPrice: 500,
      minPrice: 100,
      averageRating: 3.8,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Smoothie Spot',
      cuisineType: 'Italian',
      maxPrice: 600,
      minPrice: 400,
      averageRating: 4.0,
      logo: AppAssetsManager.japaneseRestaurantImg),
  RestaurantModel(
      name: 'Crepe Cafe',
      cuisineType: 'French',
      maxPrice: 2000,
      minPrice: 300,
      averageRating: 4.3,
      logo: AppAssetsManager.crapImg),
  RestaurantModel(
      name: 'Peruvian Paradise',
      cuisineType: 'Mexican',
      maxPrice: 900,
      minPrice: 140,
      averageRating: 4.4,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Taco Time',
      cuisineType: 'Mexican',
      maxPrice: 750,
      minPrice: 220,
      averageRating: 4.2,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Pizza Palace',
      cuisineType: 'Italian',
      maxPrice: 460,
      minPrice: 10,
      averageRating: 4.6,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Burger Barn',
      cuisineType: 'American',
      maxPrice: 1000,
      minPrice: 15,
      averageRating: 4.3,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Sushi Station',
      cuisineType: 'Japanese',
      maxPrice: 200,
      minPrice: 10,
      averageRating: 4.7,
      logo: AppAssetsManager.japaneseRestaurantImg),
  RestaurantModel(
      name: 'Salad Stop',
      cuisineType: 'Italian',
      maxPrice: 5000,
      minPrice: 100,
      averageRating: 4.2,
      logo: AppAssetsManager.crapImg),
  RestaurantModel(
      name: 'BBQ Bistro',
      cuisineType: 'American',
      maxPrice: 200,
      minPrice: 100,
      averageRating: 4.4,
      logo: AppAssetsManager.japaneseRestaurantImg),
  RestaurantModel(
      name: 'Pho Phenomenon',
      cuisineType: 'Mexican',
      maxPrice: 3200,
      minPrice: 100,
      averageRating: 4.3,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Burrito Bar',
      cuisineType: 'Mexican',
      maxPrice: 2050,
      minPrice: 100,
      averageRating: 4.1,
      logo: AppAssetsManager.japaneseRestaurantImg),
  RestaurantModel(
      name: 'Sizzle Szechuan',
      cuisineType: 'Chinese',
      maxPrice: 4200,
      minPrice: 100,
      averageRating: 4.2,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Wrap World',
      cuisineType: 'Chinese',
      maxPrice: 5800,
      minPrice: 20,
      averageRating: 4.4,
      logo: AppAssetsManager.crapImg),
  RestaurantModel(
      name: 'Juice Joint',
      cuisineType: 'Indian',
      maxPrice: 920,
      minPrice: 200,
      averageRating: 4.0,
      logo: AppAssetsManager.reShotImg),
  RestaurantModel(
      name: 'Pita Paradise',
      cuisineType: 'Mexican',
      maxPrice: 4000,
      minPrice: 1050,
      averageRating: 4.3,
      logo: AppAssetsManager.japaneseRestaurantImg),
  RestaurantModel(
      name: 'Tikka Time',
      cuisineType: 'Indian',
      maxPrice: 10000,
      minPrice: 320,
      averageRating: 4.5,
      logo: AppAssetsManager.japaneseRestaurantImg),
];
